# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class BaseModelUpload(object):

    """Implementation of the 'Base Model Upload' model.

    ساختار کلی پاسخ سرور

    Attributes:
        is_success (bool): وضعیت موفقیت درخواست
        status (int): کد وضعیت درخواست
        message (object): بدنه ی اصلی درخواست که با توجه به نوع درخواست، تغییر
            می کند
        extra_data (string): اطلاعات اضافه ی درخواست
        exception (string): اطلاعات خطاهای رخ داده

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "is_success":'isSuccess',
        "status":'status',
        "message":'message',
        "extra_data":'extraData',
        "exception":'exception'
    }

    def __init__(self,
                 is_success=None,
                 status=None,
                 message=None,
                 extra_data=None,
                 exception=None):
        """Constructor for the BaseModelUpload class"""

        # Initialize members of the class
        self.is_success = is_success
        self.status = status
        self.message = message
        self.extra_data = extra_data
        self.exception = exception


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        is_success = dictionary.get('isSuccess')
        status = dictionary.get('status')
        message = dictionary.get('message')
        extra_data = dictionary.get('extraData')
        exception = dictionary.get('exception')

        # Return an object of this model
        return cls(is_success,
                   status,
                   message,
                   extra_data,
                   exception)


