# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class DamageType(object):

    """Implementation of the 'DamageType' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        title (string): TODO: type description here.
        sort_priority (string): TODO: type description here.
        create_on (string): TODO: type description here.
        update_on (string): TODO: type description here.
        created_by (string): TODO: type description here.
        updated_by (string): TODO: type description here.
        create_on_persian_date (string): TODO: type description here.
        update_on_persian_date (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id":'id',
        "title":'title',
        "create_on":'createOn',
        "update_on":'updateOn',
        "created_by":'createdBy',
        "create_on_persian_date":'createOnPersianDate',
        "update_on_persian_date":'updateOnPersianDate',
        "sort_priority":'sortPriority',
        "updated_by":'updatedBy'
    }

    def __init__(self,
                 id=None,
                 title=None,
                 create_on=None,
                 update_on=None,
                 created_by=None,
                 create_on_persian_date=None,
                 update_on_persian_date=None,
                 sort_priority=None,
                 updated_by=None):
        """Constructor for the DamageType class"""

        # Initialize members of the class
        self.id = id
        self.title = title
        self.sort_priority = sort_priority
        self.create_on = create_on
        self.update_on = update_on
        self.created_by = created_by
        self.updated_by = updated_by
        self.create_on_persian_date = create_on_persian_date
        self.update_on_persian_date = update_on_persian_date


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        title = dictionary.get('title')
        create_on = dictionary.get('createOn')
        update_on = dictionary.get('updateOn')
        created_by = dictionary.get('createdBy')
        create_on_persian_date = dictionary.get('createOnPersianDate')
        update_on_persian_date = dictionary.get('updateOnPersianDate')
        sort_priority = dictionary.get('sortPriority')
        updated_by = dictionary.get('updatedBy')

        # Return an object of this model
        return cls(id,
                   title,
                   create_on,
                   update_on,
                   created_by,
                   create_on_persian_date,
                   update_on_persian_date,
                   sort_priority,
                   updated_by)


