# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ElectronicEquipmentInsurancePolicyFilter(object):

    """Implementation of the 'ElectronicEquipmentInsurancePolicyFilter' model.

    TODO: type model description here.

    Attributes:
        device_type_id (int): TODO: type description here.
        device_brand_id (int): TODO: type description here.
        device_model_id (int): TODO: type description here.
        build_year (string): TODO: type description here.
        device_value (string): TODO: type description here.
        franchisee_id (int): TODO: type description here.
        insurance_extra_coverage_ids (int): TODO: type description here.
        policy_term_id (int): TODO: type description here.
        insurance_centre_sub_domain_name (string): TODO: type description
            here.
        insurance_centre_id (int): TODO: type description here.
        insurance_company_id (int): TODO: type description here.
        is_search_query (bool): TODO: type description here.
        gift_code (string): TODO: type description here.
        customer_user_id (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "is_search_query":'isSearchQuery',
        "device_type_id":'deviceTypeId',
        "device_brand_id":'deviceBrandId',
        "device_model_id":'deviceModelId',
        "build_year":'buildYear',
        "device_value":'deviceValue',
        "franchisee_id":'franchiseeId',
        "insurance_extra_coverage_ids":'insuranceExtraCoverageIds',
        "policy_term_id":'policyTermId',
        "insurance_centre_sub_domain_name":'insuranceCentreSubDomainName',
        "insurance_centre_id":'insuranceCentreId',
        "insurance_company_id":'insuranceCompanyId',
        "gift_code":'giftCode',
        "customer_user_id":'customerUserId'
    }

    def __init__(self,
                 is_search_query=None,
                 device_type_id=None,
                 device_brand_id=None,
                 device_model_id=None,
                 build_year=None,
                 device_value=None,
                 franchisee_id=None,
                 insurance_extra_coverage_ids=None,
                 policy_term_id=None,
                 insurance_centre_sub_domain_name=None,
                 insurance_centre_id=None,
                 insurance_company_id=None,
                 gift_code=None,
                 customer_user_id=None):
        """Constructor for the ElectronicEquipmentInsurancePolicyFilter class"""

        # Initialize members of the class
        self.device_type_id = device_type_id
        self.device_brand_id = device_brand_id
        self.device_model_id = device_model_id
        self.build_year = build_year
        self.device_value = device_value
        self.franchisee_id = franchisee_id
        self.insurance_extra_coverage_ids = insurance_extra_coverage_ids
        self.policy_term_id = policy_term_id
        self.insurance_centre_sub_domain_name = insurance_centre_sub_domain_name
        self.insurance_centre_id = insurance_centre_id
        self.insurance_company_id = insurance_company_id
        self.is_search_query = is_search_query
        self.gift_code = gift_code
        self.customer_user_id = customer_user_id


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        is_search_query = dictionary.get('isSearchQuery')
        device_type_id = dictionary.get('deviceTypeId')
        device_brand_id = dictionary.get('deviceBrandId')
        device_model_id = dictionary.get('deviceModelId')
        build_year = dictionary.get('buildYear')
        device_value = dictionary.get('deviceValue')
        franchisee_id = dictionary.get('franchiseeId')
        insurance_extra_coverage_ids = dictionary.get('insuranceExtraCoverageIds')
        policy_term_id = dictionary.get('policyTermId')
        insurance_centre_sub_domain_name = dictionary.get('insuranceCentreSubDomainName')
        insurance_centre_id = dictionary.get('insuranceCentreId')
        insurance_company_id = dictionary.get('insuranceCompanyId')
        gift_code = dictionary.get('giftCode')
        customer_user_id = dictionary.get('customerUserId')

        # Return an object of this model
        return cls(is_search_query,
                   device_type_id,
                   device_brand_id,
                   device_model_id,
                   build_year,
                   device_value,
                   franchisee_id,
                   insurance_extra_coverage_ids,
                   policy_term_id,
                   insurance_centre_sub_domain_name,
                   insurance_centre_id,
                   insurance_company_id,
                   gift_code,
                   customer_user_id)


