# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ElevatorInsurancePolicyExtendView(object):

    """Implementation of the 'ElevatorInsurancePolicyExtendView' model.

    TODO: type model description here.

    Attributes:
        building_use_type_param_id (string): TODO: type description here.
        elevator_type_param_id (string): TODO: type description here.
        floors (string): TODO: type description here.
        elevator_capacity (string): TODO: type description here.
        elevator_capacity_cargo (string): TODO: type description here.
        defect_organ_coverage_id (string): TODO: type description here.
        death_capital_coverage_id (string): TODO: type description here.
        financial_coverage_id (string): TODO: type description here.
        medical_cost_coverage_id (string): TODO: type description here.
        risk_level_discount_rate (string): TODO: type description here.
        insurance_risk_level_id (string): TODO: type description here.
        discount_rate (string): TODO: type description here.
        city_id (string): TODO: type description here.
        province_id (string): TODO: type description here.
        zip_code (string): TODO: type description here.
        address_place_building (string): TODO: type description here.
        owner_coverage (bool): TODO: type description here.
        risk_level_discount (int): TODO: type description here.
        base_premium (string): TODO: type description here.
        all_premium (string): TODO: type description here.
        insurance_company_discount_rate (int): TODO: type description here.
        insurance_company_discount (int): TODO: type description here.
        insurance_centre_discount (int): TODO: type description here.
        coupen_discount (int): TODO: type description here.
        all_discount (int): TODO: type description here.
        exchange_premium (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "owner_coverage":'ownerCoverage',
        "risk_level_discount":'riskLevelDiscount',
        "insurance_company_discount_rate":'insuranceCompanyDiscountRate',
        "insurance_company_discount":'insuranceCompanyDiscount',
        "insurance_centre_discount":'insuranceCentreDiscount',
        "coupen_discount":'coupenDiscount',
        "all_discount":'allDiscount',
        "exchange_premium":'exchangePremium',
        "building_use_type_param_id":'buildingUseTypeParamId',
        "elevator_type_param_id":'elevatorTypeParamId',
        "floors":'floors',
        "elevator_capacity":'elevatorCapacity',
        "elevator_capacity_cargo":'elevatorCapacityCargo',
        "defect_organ_coverage_id":'defectOrganCoverageId',
        "death_capital_coverage_id":'deathCapitalCoverageId',
        "financial_coverage_id":'financialCoverageId',
        "medical_cost_coverage_id":'medicalCostCoverageId',
        "risk_level_discount_rate":'riskLevelDiscountRate',
        "insurance_risk_level_id":'insuranceRiskLevelId',
        "discount_rate":'discountRate',
        "city_id":'cityId',
        "province_id":'provinceId',
        "zip_code":'zipCode',
        "address_place_building":'addressPlaceBuilding',
        "base_premium":'basePremium',
        "all_premium":'allPremium'
    }

    def __init__(self,
                 owner_coverage=None,
                 risk_level_discount=None,
                 insurance_company_discount_rate=None,
                 insurance_company_discount=None,
                 insurance_centre_discount=None,
                 coupen_discount=None,
                 all_discount=None,
                 exchange_premium=None,
                 building_use_type_param_id=None,
                 elevator_type_param_id=None,
                 floors=None,
                 elevator_capacity=None,
                 elevator_capacity_cargo=None,
                 defect_organ_coverage_id=None,
                 death_capital_coverage_id=None,
                 financial_coverage_id=None,
                 medical_cost_coverage_id=None,
                 risk_level_discount_rate=None,
                 insurance_risk_level_id=None,
                 discount_rate=None,
                 city_id=None,
                 province_id=None,
                 zip_code=None,
                 address_place_building=None,
                 base_premium=None,
                 all_premium=None):
        """Constructor for the ElevatorInsurancePolicyExtendView class"""

        # Initialize members of the class
        self.building_use_type_param_id = building_use_type_param_id
        self.elevator_type_param_id = elevator_type_param_id
        self.floors = floors
        self.elevator_capacity = elevator_capacity
        self.elevator_capacity_cargo = elevator_capacity_cargo
        self.defect_organ_coverage_id = defect_organ_coverage_id
        self.death_capital_coverage_id = death_capital_coverage_id
        self.financial_coverage_id = financial_coverage_id
        self.medical_cost_coverage_id = medical_cost_coverage_id
        self.risk_level_discount_rate = risk_level_discount_rate
        self.insurance_risk_level_id = insurance_risk_level_id
        self.discount_rate = discount_rate
        self.city_id = city_id
        self.province_id = province_id
        self.zip_code = zip_code
        self.address_place_building = address_place_building
        self.owner_coverage = owner_coverage
        self.risk_level_discount = risk_level_discount
        self.base_premium = base_premium
        self.all_premium = all_premium
        self.insurance_company_discount_rate = insurance_company_discount_rate
        self.insurance_company_discount = insurance_company_discount
        self.insurance_centre_discount = insurance_centre_discount
        self.coupen_discount = coupen_discount
        self.all_discount = all_discount
        self.exchange_premium = exchange_premium


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        owner_coverage = dictionary.get('ownerCoverage')
        risk_level_discount = dictionary.get('riskLevelDiscount')
        insurance_company_discount_rate = dictionary.get('insuranceCompanyDiscountRate')
        insurance_company_discount = dictionary.get('insuranceCompanyDiscount')
        insurance_centre_discount = dictionary.get('insuranceCentreDiscount')
        coupen_discount = dictionary.get('coupenDiscount')
        all_discount = dictionary.get('allDiscount')
        exchange_premium = dictionary.get('exchangePremium')
        building_use_type_param_id = dictionary.get('buildingUseTypeParamId')
        elevator_type_param_id = dictionary.get('elevatorTypeParamId')
        floors = dictionary.get('floors')
        elevator_capacity = dictionary.get('elevatorCapacity')
        elevator_capacity_cargo = dictionary.get('elevatorCapacityCargo')
        defect_organ_coverage_id = dictionary.get('defectOrganCoverageId')
        death_capital_coverage_id = dictionary.get('deathCapitalCoverageId')
        financial_coverage_id = dictionary.get('financialCoverageId')
        medical_cost_coverage_id = dictionary.get('medicalCostCoverageId')
        risk_level_discount_rate = dictionary.get('riskLevelDiscountRate')
        insurance_risk_level_id = dictionary.get('insuranceRiskLevelId')
        discount_rate = dictionary.get('discountRate')
        city_id = dictionary.get('cityId')
        province_id = dictionary.get('provinceId')
        zip_code = dictionary.get('zipCode')
        address_place_building = dictionary.get('addressPlaceBuilding')
        base_premium = dictionary.get('basePremium')
        all_premium = dictionary.get('allPremium')

        # Return an object of this model
        return cls(owner_coverage,
                   risk_level_discount,
                   insurance_company_discount_rate,
                   insurance_company_discount,
                   insurance_centre_discount,
                   coupen_discount,
                   all_discount,
                   exchange_premium,
                   building_use_type_param_id,
                   elevator_type_param_id,
                   floors,
                   elevator_capacity,
                   elevator_capacity_cargo,
                   defect_organ_coverage_id,
                   death_capital_coverage_id,
                   financial_coverage_id,
                   medical_cost_coverage_id,
                   risk_level_discount_rate,
                   insurance_risk_level_id,
                   discount_rate,
                   city_id,
                   province_id,
                   zip_code,
                   address_place_building,
                   base_premium,
                   all_premium)


