# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ExtraDataBaseModelPortalLandingPage(object):

    """Implementation of the 'ExtraData Base Model PortalLandingPage' model.

    TODO: type model description here.

    Attributes:
        has_plan (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "has_plan":'hasPlan'
    }

    def __init__(self,
                 has_plan=None):
        """Constructor for the ExtraDataBaseModelPortalLandingPage class"""

        # Initialize members of the class
        self.has_plan = has_plan


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        has_plan = dictionary.get('hasPlan')

        # Return an object of this model
        return cls(has_plan)


