# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class ExtraData(object):

    """Implementation of the 'ExtraData' model.

    با توجه به API ممکن است تغییر کند

    Attributes:
        alias_name (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "alias_name":'aliasName'
    }

    def __init__(self,
                 alias_name=None):
        """Constructor for the ExtraData class"""

        # Initialize members of the class
        self.alias_name = alias_name


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        alias_name = dictionary.get('aliasName')

        # Return an object of this model
        return cls(alias_name)


