# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class FireInsurancePolicyExtendView(object):

    """Implementation of the 'FireInsurancePolicyExtendView' model.

    TODO: type model description here.

    Attributes:
        building_type_param_id (string): TODO: type description here.
        skeleton_type_building_param_id (string): TODO: type description
            here.
        building_use_type_param_id (string): TODO: type description here.
        unit_count (string): TODO: type description here.
        every_square_meter_coverage_rate_id (int): TODO: type description
            here.
        city_id (string): TODO: type description here.
        province_id (string): TODO: type description here.
        building_area (string): TODO: type description here.
        value_of_appliances_furnishing (string): TODO: type description here.
        insurance_coverage_ids (string): TODO: type description here.
        only_appliances_furnishings (bool): TODO: type description here.
        insurance_coverage_price (string): TODO: type description here.
        insurance_policy_commitment_ceiling (string): TODO: type description
            here.
        value_per_square_meter_rate (string): TODO: type description here.
        build_year (string): TODO: type description here.
        zip_code (string): TODO: type description here.
        address_place_building (string): TODO: type description here.
        risk_level_discount (int): TODO: type description here.
        base_premium (string): TODO: type description here.
        all_premium (string): TODO: type description here.
        insurance_company_discount_rate (int): TODO: type description here.
        insurance_company_discount (int): TODO: type description here.
        insurance_centre_discount (int): TODO: type description here.
        coupen_discount (int): TODO: type description here.
        all_discount (int): TODO: type description here.
        exchange_premium (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "every_square_meter_coverage_rate_id":'everySquareMeterCoverageRateId',
        "only_appliances_furnishings":'onlyAppliancesFurnishings',
        "risk_level_discount":'riskLevelDiscount',
        "insurance_company_discount_rate":'insuranceCompanyDiscountRate',
        "insurance_company_discount":'insuranceCompanyDiscount',
        "insurance_centre_discount":'insuranceCentreDiscount',
        "coupen_discount":'coupenDiscount',
        "all_discount":'allDiscount',
        "exchange_premium":'exchangePremium',
        "building_type_param_id":'buildingTypeParamId',
        "skeleton_type_building_param_id":'skeletonTypeBuildingParamId',
        "building_use_type_param_id":'buildingUseTypeParamId',
        "unit_count":'unitCount',
        "city_id":'cityId',
        "province_id":'provinceId',
        "building_area":'buildingArea',
        "value_of_appliances_furnishing":'valueOfAppliancesFurnishing',
        "insurance_coverage_ids":'_InsuranceCoverageIds',
        "insurance_coverage_price":'insuranceCoveragePrice',
        "insurance_policy_commitment_ceiling":'insurancePolicyCommitmentCeiling',
        "value_per_square_meter_rate":'valuePerSquareMeterRate',
        "build_year":'buildYear',
        "zip_code":'zipCode',
        "address_place_building":'addressPlaceBuilding',
        "base_premium":'basePremium',
        "all_premium":'allPremium'
    }

    def __init__(self,
                 every_square_meter_coverage_rate_id=None,
                 only_appliances_furnishings=None,
                 risk_level_discount=None,
                 insurance_company_discount_rate=None,
                 insurance_company_discount=None,
                 insurance_centre_discount=None,
                 coupen_discount=None,
                 all_discount=None,
                 exchange_premium=None,
                 building_type_param_id=None,
                 skeleton_type_building_param_id=None,
                 building_use_type_param_id=None,
                 unit_count=None,
                 city_id=None,
                 province_id=None,
                 building_area=None,
                 value_of_appliances_furnishing=None,
                 insurance_coverage_ids=None,
                 insurance_coverage_price=None,
                 insurance_policy_commitment_ceiling=None,
                 value_per_square_meter_rate=None,
                 build_year=None,
                 zip_code=None,
                 address_place_building=None,
                 base_premium=None,
                 all_premium=None):
        """Constructor for the FireInsurancePolicyExtendView class"""

        # Initialize members of the class
        self.building_type_param_id = building_type_param_id
        self.skeleton_type_building_param_id = skeleton_type_building_param_id
        self.building_use_type_param_id = building_use_type_param_id
        self.unit_count = unit_count
        self.every_square_meter_coverage_rate_id = every_square_meter_coverage_rate_id
        self.city_id = city_id
        self.province_id = province_id
        self.building_area = building_area
        self.value_of_appliances_furnishing = value_of_appliances_furnishing
        self.insurance_coverage_ids = insurance_coverage_ids
        self.only_appliances_furnishings = only_appliances_furnishings
        self.insurance_coverage_price = insurance_coverage_price
        self.insurance_policy_commitment_ceiling = insurance_policy_commitment_ceiling
        self.value_per_square_meter_rate = value_per_square_meter_rate
        self.build_year = build_year
        self.zip_code = zip_code
        self.address_place_building = address_place_building
        self.risk_level_discount = risk_level_discount
        self.base_premium = base_premium
        self.all_premium = all_premium
        self.insurance_company_discount_rate = insurance_company_discount_rate
        self.insurance_company_discount = insurance_company_discount
        self.insurance_centre_discount = insurance_centre_discount
        self.coupen_discount = coupen_discount
        self.all_discount = all_discount
        self.exchange_premium = exchange_premium


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        every_square_meter_coverage_rate_id = dictionary.get('everySquareMeterCoverageRateId')
        only_appliances_furnishings = dictionary.get('onlyAppliancesFurnishings')
        risk_level_discount = dictionary.get('riskLevelDiscount')
        insurance_company_discount_rate = dictionary.get('insuranceCompanyDiscountRate')
        insurance_company_discount = dictionary.get('insuranceCompanyDiscount')
        insurance_centre_discount = dictionary.get('insuranceCentreDiscount')
        coupen_discount = dictionary.get('coupenDiscount')
        all_discount = dictionary.get('allDiscount')
        exchange_premium = dictionary.get('exchangePremium')
        building_type_param_id = dictionary.get('buildingTypeParamId')
        skeleton_type_building_param_id = dictionary.get('skeletonTypeBuildingParamId')
        building_use_type_param_id = dictionary.get('buildingUseTypeParamId')
        unit_count = dictionary.get('unitCount')
        city_id = dictionary.get('cityId')
        province_id = dictionary.get('provinceId')
        building_area = dictionary.get('buildingArea')
        value_of_appliances_furnishing = dictionary.get('valueOfAppliancesFurnishing')
        insurance_coverage_ids = dictionary.get('_InsuranceCoverageIds')
        insurance_coverage_price = dictionary.get('insuranceCoveragePrice')
        insurance_policy_commitment_ceiling = dictionary.get('insurancePolicyCommitmentCeiling')
        value_per_square_meter_rate = dictionary.get('valuePerSquareMeterRate')
        build_year = dictionary.get('buildYear')
        zip_code = dictionary.get('zipCode')
        address_place_building = dictionary.get('addressPlaceBuilding')
        base_premium = dictionary.get('basePremium')
        all_premium = dictionary.get('allPremium')

        # Return an object of this model
        return cls(every_square_meter_coverage_rate_id,
                   only_appliances_furnishings,
                   risk_level_discount,
                   insurance_company_discount_rate,
                   insurance_company_discount,
                   insurance_centre_discount,
                   coupen_discount,
                   all_discount,
                   exchange_premium,
                   building_type_param_id,
                   skeleton_type_building_param_id,
                   building_use_type_param_id,
                   unit_count,
                   city_id,
                   province_id,
                   building_area,
                   value_of_appliances_furnishing,
                   insurance_coverage_ids,
                   insurance_coverage_price,
                   insurance_policy_commitment_ceiling,
                   value_per_square_meter_rate,
                   build_year,
                   zip_code,
                   address_place_building,
                   base_premium,
                   all_premium)


