# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class GetAccessTokenUserInfo(object):

    """Implementation of the 'get Access Token User Info' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        access_token (string): TODO: type description here.
        expires_in (string): TODO: type description here.
        refresh_token (string): TODO: type description here.
        error (string): TODO: type description here.
        user_name (string): TODO: type description here.
        insurance_centre_name (string): TODO: type description here.
        insurance_centre_logo (string): TODO: type description here.
        insurance_centre_favicon (string): TODO: type description here.
        licensed (bool): TODO: type description here.
        email (string): TODO: type description here.
        insurance_centre_type (int): TODO: type description here.
        avatar_url (string): TODO: type description here.
        alias_name (string): TODO: type description here.
        user_group (int): TODO: type description here.
        user_group_title (string): TODO: type description here.
        role_ids (list of string): TODO: type description here.
        role_titles (string): TODO: type description here.
        unlimited_account (bool): TODO: type description here.
        role_permissions (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id":'id',
        "access_token":'access_token',
        "expires_in":'expires_in',
        "refresh_token":'refresh_token',
        "user_name":'userName',
        "insurance_centre_name":'insuranceCentreName',
        "insurance_centre_logo":'insuranceCentreLogo',
        "licensed":'licensed',
        "email":'email',
        "insurance_centre_type":'insuranceCentreType',
        "avatar_url":'avatarUrl',
        "alias_name":'aliasName',
        "user_group":'userGroup',
        "user_group_title":'userGroupTitle',
        "role_ids":'roleIds',
        "role_titles":'roleTitles',
        "unlimited_account":'unlimitedAccount',
        "error":'error',
        "insurance_centre_favicon":'insuranceCentreFavicon',
        "role_permissions":'rolePermissions'
    }

    def __init__(self,
                 id=None,
                 access_token=None,
                 expires_in=None,
                 refresh_token=None,
                 user_name=None,
                 insurance_centre_name=None,
                 insurance_centre_logo=None,
                 licensed=None,
                 email=None,
                 insurance_centre_type=None,
                 avatar_url=None,
                 alias_name=None,
                 user_group=None,
                 user_group_title=None,
                 role_ids=None,
                 role_titles=None,
                 unlimited_account=None,
                 error=None,
                 insurance_centre_favicon=None,
                 role_permissions=None):
        """Constructor for the GetAccessTokenUserInfo class"""

        # Initialize members of the class
        self.id = id
        self.access_token = access_token
        self.expires_in = expires_in
        self.refresh_token = refresh_token
        self.error = error
        self.user_name = user_name
        self.insurance_centre_name = insurance_centre_name
        self.insurance_centre_logo = insurance_centre_logo
        self.insurance_centre_favicon = insurance_centre_favicon
        self.licensed = licensed
        self.email = email
        self.insurance_centre_type = insurance_centre_type
        self.avatar_url = avatar_url
        self.alias_name = alias_name
        self.user_group = user_group
        self.user_group_title = user_group_title
        self.role_ids = role_ids
        self.role_titles = role_titles
        self.unlimited_account = unlimited_account
        self.role_permissions = role_permissions


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        access_token = dictionary.get('access_token')
        expires_in = dictionary.get('expires_in')
        refresh_token = dictionary.get('refresh_token')
        user_name = dictionary.get('userName')
        insurance_centre_name = dictionary.get('insuranceCentreName')
        insurance_centre_logo = dictionary.get('insuranceCentreLogo')
        licensed = dictionary.get('licensed')
        email = dictionary.get('email')
        insurance_centre_type = dictionary.get('insuranceCentreType')
        avatar_url = dictionary.get('avatarUrl')
        alias_name = dictionary.get('aliasName')
        user_group = dictionary.get('userGroup')
        user_group_title = dictionary.get('userGroupTitle')
        role_ids = dictionary.get('roleIds')
        role_titles = dictionary.get('roleTitles')
        unlimited_account = dictionary.get('unlimitedAccount')
        error = dictionary.get('error')
        insurance_centre_favicon = dictionary.get('insuranceCentreFavicon')
        role_permissions = dictionary.get('rolePermissions')

        # Return an object of this model
        return cls(id,
                   access_token,
                   expires_in,
                   refresh_token,
                   user_name,
                   insurance_centre_name,
                   insurance_centre_logo,
                   licensed,
                   email,
                   insurance_centre_type,
                   avatar_url,
                   alias_name,
                   user_group,
                   user_group_title,
                   role_ids,
                   role_titles,
                   unlimited_account,
                   error,
                   insurance_centre_favicon,
                   role_permissions)


