# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class InsuranceExtraCoverageExtraData(object):

    """Implementation of the 'InsuranceExtraCoverage ExtraData' model.

    TODO: type model description here.

    Attributes:
        default_status (bool): TODO: type description here.
        requiring_expert_visit (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "default_status":'defaultStatus',
        "requiring_expert_visit":'requiringExpertVisit'
    }

    def __init__(self,
                 default_status=None,
                 requiring_expert_visit=None):
        """Constructor for the InsuranceExtraCoverageExtraData class"""

        # Initialize members of the class
        self.default_status = default_status
        self.requiring_expert_visit = requiring_expert_visit


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        default_status = dictionary.get('defaultStatus')
        requiring_expert_visit = dictionary.get('requiringExpertVisit')

        # Return an object of this model
        return cls(default_status,
                   requiring_expert_visit)


