# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class InsuranceCentrePortal(object):

    """Implementation of the 'InsuranceCentrePortal' model.

    TODO: type model description here.

    Attributes:
        insurance_centre_id (int): TODO: type description here.
        centre_name (string): TODO: type description here.
        sub_domain_name (string): TODO: type description here.
        title (string): TODO: type description here.
        sub_title (string): TODO: type description here.
        contact_us (string): TODO: type description here.
        about_us (string): TODO: type description here.
        our_service (string): TODO: type description here.
        terms_conditions (string): TODO: type description here.
        copyright (string): TODO: type description here.
        header_title (string): TODO: type description here.
        header_body (string): TODO: type description here.
        footer_color (string): TODO: type description here.
        background_color (string): TODO: type description here.
        licensed (bool): TODO: type description here.
        default_logo (string): TODO: type description here.
        title_color (string): TODO: type description here.
        sub_title_color (string): TODO: type description here.
        e_trust_symbol (string): TODO: type description here.
        digital_media_organizer_symbol (string): TODO: type description here.
        google_plus (string): TODO: type description here.
        telegram (string): TODO: type description here.
        instagram (string): TODO: type description here.
        face_book (string): TODO: type description here.
        twitter (string): TODO: type description here.
        saturday_to_wednesday_from_hour (string): TODO: type description
            here.
        saturday_to_wednesday_to_hour (string): TODO: type description here.
        thursday_from_hour (string): TODO: type description here.
        thursday_to_hour (string): TODO: type description here.
        friday_from_hour (string): TODO: type description here.
        friday_to_hour (string): TODO: type description here.
        meta_media_file_header_id (int): TODO: type description here.
        meta_media_file_header_url (string): TODO: type description here.
        meta_media_file_logo_id (int): TODO: type description here.
        meta_media_file_logo_url (string): TODO: type description here.
        meta_media_file_favicon_id (int): TODO: type description here.
        meta_media_file_favicon_url (string): TODO: type description here.
        meta_media_file_footer_id (string): TODO: type description here.
        meta_media_file_footer_url (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "insurance_centre_id":'insuranceCentreId',
        "centre_name":'centreName',
        "sub_domain_name":'subDomainName',
        "title":'title',
        "sub_title":'subTitle',
        "about_us":'aboutUs',
        "our_service":'ourService',
        "licensed":'licensed',
        "title_color":'titleColor',
        "sub_title_color":'subTitleColor',
        "google_plus":'googlePlus',
        "telegram":'telegram',
        "instagram":'instagram',
        "face_book":'faceBook',
        "twitter":'twitter',
        "meta_media_file_header_id":'metaMediaFileHeaderId',
        "meta_media_file_header_url":'metaMediaFileHeaderUrl',
        "meta_media_file_logo_id":'metaMediaFileLogoId',
        "meta_media_file_logo_url":'metaMediaFileLogoUrl',
        "meta_media_file_favicon_id":'metaMediaFileFaviconId',
        "meta_media_file_favicon_url":'metaMediaFileFaviconUrl',
        "contact_us":'contactUs',
        "terms_conditions":'termsConditions',
        "copyright":'copyright',
        "header_title":'headerTitle',
        "header_body":'headerBody',
        "footer_color":'footerColor',
        "background_color":'backgroundColor',
        "default_logo":'defaultLogo',
        "e_trust_symbol":'eTrustSymbol',
        "digital_media_organizer_symbol":'digitalMediaOrganizerSymbol',
        "saturday_to_wednesday_from_hour":'saturdayToWednesdayFromHour',
        "saturday_to_wednesday_to_hour":'saturdayToWednesdayToHour',
        "thursday_from_hour":'thursdayFromHour',
        "thursday_to_hour":'thursdayToHour',
        "friday_from_hour":'fridayFromHour',
        "friday_to_hour":'fridayToHour',
        "meta_media_file_footer_id":'metaMediaFileFooterId',
        "meta_media_file_footer_url":'metaMediaFileFooterUrl'
    }

    def __init__(self,
                 insurance_centre_id=None,
                 centre_name=None,
                 sub_domain_name=None,
                 title=None,
                 sub_title=None,
                 about_us=None,
                 our_service=None,
                 licensed=None,
                 title_color=None,
                 sub_title_color=None,
                 google_plus=None,
                 telegram=None,
                 instagram=None,
                 face_book=None,
                 twitter=None,
                 meta_media_file_header_id=None,
                 meta_media_file_header_url=None,
                 meta_media_file_logo_id=None,
                 meta_media_file_logo_url=None,
                 meta_media_file_favicon_id=None,
                 meta_media_file_favicon_url=None,
                 contact_us=None,
                 terms_conditions=None,
                 copyright=None,
                 header_title=None,
                 header_body=None,
                 footer_color=None,
                 background_color=None,
                 default_logo=None,
                 e_trust_symbol=None,
                 digital_media_organizer_symbol=None,
                 saturday_to_wednesday_from_hour=None,
                 saturday_to_wednesday_to_hour=None,
                 thursday_from_hour=None,
                 thursday_to_hour=None,
                 friday_from_hour=None,
                 friday_to_hour=None,
                 meta_media_file_footer_id=None,
                 meta_media_file_footer_url=None):
        """Constructor for the InsuranceCentrePortal class"""

        # Initialize members of the class
        self.insurance_centre_id = insurance_centre_id
        self.centre_name = centre_name
        self.sub_domain_name = sub_domain_name
        self.title = title
        self.sub_title = sub_title
        self.contact_us = contact_us
        self.about_us = about_us
        self.our_service = our_service
        self.terms_conditions = terms_conditions
        self.copyright = copyright
        self.header_title = header_title
        self.header_body = header_body
        self.footer_color = footer_color
        self.background_color = background_color
        self.licensed = licensed
        self.default_logo = default_logo
        self.title_color = title_color
        self.sub_title_color = sub_title_color
        self.e_trust_symbol = e_trust_symbol
        self.digital_media_organizer_symbol = digital_media_organizer_symbol
        self.google_plus = google_plus
        self.telegram = telegram
        self.instagram = instagram
        self.face_book = face_book
        self.twitter = twitter
        self.saturday_to_wednesday_from_hour = saturday_to_wednesday_from_hour
        self.saturday_to_wednesday_to_hour = saturday_to_wednesday_to_hour
        self.thursday_from_hour = thursday_from_hour
        self.thursday_to_hour = thursday_to_hour
        self.friday_from_hour = friday_from_hour
        self.friday_to_hour = friday_to_hour
        self.meta_media_file_header_id = meta_media_file_header_id
        self.meta_media_file_header_url = meta_media_file_header_url
        self.meta_media_file_logo_id = meta_media_file_logo_id
        self.meta_media_file_logo_url = meta_media_file_logo_url
        self.meta_media_file_favicon_id = meta_media_file_favicon_id
        self.meta_media_file_favicon_url = meta_media_file_favicon_url
        self.meta_media_file_footer_id = meta_media_file_footer_id
        self.meta_media_file_footer_url = meta_media_file_footer_url


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        insurance_centre_id = dictionary.get('insuranceCentreId')
        centre_name = dictionary.get('centreName')
        sub_domain_name = dictionary.get('subDomainName')
        title = dictionary.get('title')
        sub_title = dictionary.get('subTitle')
        about_us = dictionary.get('aboutUs')
        our_service = dictionary.get('ourService')
        licensed = dictionary.get('licensed')
        title_color = dictionary.get('titleColor')
        sub_title_color = dictionary.get('subTitleColor')
        google_plus = dictionary.get('googlePlus')
        telegram = dictionary.get('telegram')
        instagram = dictionary.get('instagram')
        face_book = dictionary.get('faceBook')
        twitter = dictionary.get('twitter')
        meta_media_file_header_id = dictionary.get('metaMediaFileHeaderId')
        meta_media_file_header_url = dictionary.get('metaMediaFileHeaderUrl')
        meta_media_file_logo_id = dictionary.get('metaMediaFileLogoId')
        meta_media_file_logo_url = dictionary.get('metaMediaFileLogoUrl')
        meta_media_file_favicon_id = dictionary.get('metaMediaFileFaviconId')
        meta_media_file_favicon_url = dictionary.get('metaMediaFileFaviconUrl')
        contact_us = dictionary.get('contactUs')
        terms_conditions = dictionary.get('termsConditions')
        copyright = dictionary.get('copyright')
        header_title = dictionary.get('headerTitle')
        header_body = dictionary.get('headerBody')
        footer_color = dictionary.get('footerColor')
        background_color = dictionary.get('backgroundColor')
        default_logo = dictionary.get('defaultLogo')
        e_trust_symbol = dictionary.get('eTrustSymbol')
        digital_media_organizer_symbol = dictionary.get('digitalMediaOrganizerSymbol')
        saturday_to_wednesday_from_hour = dictionary.get('saturdayToWednesdayFromHour')
        saturday_to_wednesday_to_hour = dictionary.get('saturdayToWednesdayToHour')
        thursday_from_hour = dictionary.get('thursdayFromHour')
        thursday_to_hour = dictionary.get('thursdayToHour')
        friday_from_hour = dictionary.get('fridayFromHour')
        friday_to_hour = dictionary.get('fridayToHour')
        meta_media_file_footer_id = dictionary.get('metaMediaFileFooterId')
        meta_media_file_footer_url = dictionary.get('metaMediaFileFooterUrl')

        # Return an object of this model
        return cls(insurance_centre_id,
                   centre_name,
                   sub_domain_name,
                   title,
                   sub_title,
                   about_us,
                   our_service,
                   licensed,
                   title_color,
                   sub_title_color,
                   google_plus,
                   telegram,
                   instagram,
                   face_book,
                   twitter,
                   meta_media_file_header_id,
                   meta_media_file_header_url,
                   meta_media_file_logo_id,
                   meta_media_file_logo_url,
                   meta_media_file_favicon_id,
                   meta_media_file_favicon_url,
                   contact_us,
                   terms_conditions,
                   copyright,
                   header_title,
                   header_body,
                   footer_color,
                   background_color,
                   default_logo,
                   e_trust_symbol,
                   digital_media_organizer_symbol,
                   saturday_to_wednesday_from_hour,
                   saturday_to_wednesday_to_hour,
                   thursday_from_hour,
                   thursday_to_hour,
                   friday_from_hour,
                   friday_to_hour,
                   meta_media_file_footer_id,
                   meta_media_file_footer_url)


