# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import easybimehlanding.models.activity_area
import easybimehlanding.models.expertise
import easybimehlanding.models.commitment_ceiling
import easybimehlanding.models.insurance_company
import easybimehlanding.models.insurance_risk_level
import easybimehlanding.models.insurance_policy_term
import easybimehlanding.models.province
import easybimehlanding.models.shipping_type
import easybimehlanding.models.post_type
import easybimehlanding.models.insurance_policy_condition
import easybimehlanding.models.insurance_data_liability_doctor_insurance

class LiabilityDoctorInsurance(object):

    """Implementation of the 'LiabilityDoctorInsurance' model.

    مدل اصلی بیمه ی مسئولیت پزشکان

    Attributes:
        has_plan (bool): آیا طرح بیمه ای فعالی دارد؟
        activity_area (list of ActivityArea): حوزه ی فعالیت
        expertises (list of Expertise): لیست تخصص ها
        commitment_ceilings (list of CommitmentCeiling): لیست سقف تعهد
        physical_commitment (int): مبلغ تعهد
        insurance_companies (list of InsuranceCompany): لیست شرکت های بیمه
        insurance_risk_levels (list of InsuranceRiskLevel): تخفیف های بیمه ای
        insurance_policy_terms (list of InsurancePolicyTerm): دوره های بیمه
            ای
        provinces (list of Province): لیست استان ها
        cities (list of string): لیست شهر ها
        city_regions (list of string): لیست مناطق شهر
        shipping_types (list of ShippingType): نحوه ی ارسال
        post_types (list of PostType): روش های پستی
        insurance_policy_condition (InsurancePolicyCondition): شرایط بیمه
            نامه
        insurance_data (InsuranceDataLiabilityDoctorInsurance): اطلاعات بیمه
            نامه

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "has_plan":'hasPlan',
        "activity_area":'activityArea',
        "expertises":'expertises',
        "commitment_ceilings":'commitmentCeilings',
        "physical_commitment":'physicalCommitment',
        "insurance_companies":'insuranceCompanies',
        "insurance_risk_levels":'insuranceRiskLevels',
        "insurance_policy_terms":'insurancePolicyTerms',
        "provinces":'provinces',
        "cities":'cities',
        "city_regions":'cityRegions',
        "shipping_types":'shippingTypes',
        "post_types":'postTypes',
        "insurance_policy_condition":'insurancePolicyCondition',
        "insurance_data":'insuranceData'
    }

    def __init__(self,
                 has_plan=None,
                 activity_area=None,
                 expertises=None,
                 commitment_ceilings=None,
                 physical_commitment=None,
                 insurance_companies=None,
                 insurance_risk_levels=None,
                 insurance_policy_terms=None,
                 provinces=None,
                 cities=None,
                 city_regions=None,
                 shipping_types=None,
                 post_types=None,
                 insurance_policy_condition=None,
                 insurance_data=None):
        """Constructor for the LiabilityDoctorInsurance class"""

        # Initialize members of the class
        self.has_plan = has_plan
        self.activity_area = activity_area
        self.expertises = expertises
        self.commitment_ceilings = commitment_ceilings
        self.physical_commitment = physical_commitment
        self.insurance_companies = insurance_companies
        self.insurance_risk_levels = insurance_risk_levels
        self.insurance_policy_terms = insurance_policy_terms
        self.provinces = provinces
        self.cities = cities
        self.city_regions = city_regions
        self.shipping_types = shipping_types
        self.post_types = post_types
        self.insurance_policy_condition = insurance_policy_condition
        self.insurance_data = insurance_data


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        has_plan = dictionary.get('hasPlan')
        activity_area = None
        if dictionary.get('activityArea') != None:
            activity_area = list()
            for structure in dictionary.get('activityArea'):
                activity_area.append(easybimehlanding.models.activity_area.ActivityArea.from_dictionary(structure))
        expertises = None
        if dictionary.get('expertises') != None:
            expertises = list()
            for structure in dictionary.get('expertises'):
                expertises.append(easybimehlanding.models.expertise.Expertise.from_dictionary(structure))
        commitment_ceilings = None
        if dictionary.get('commitmentCeilings') != None:
            commitment_ceilings = list()
            for structure in dictionary.get('commitmentCeilings'):
                commitment_ceilings.append(easybimehlanding.models.commitment_ceiling.CommitmentCeiling.from_dictionary(structure))
        physical_commitment = dictionary.get('physicalCommitment')
        insurance_companies = None
        if dictionary.get('insuranceCompanies') != None:
            insurance_companies = list()
            for structure in dictionary.get('insuranceCompanies'):
                insurance_companies.append(easybimehlanding.models.insurance_company.InsuranceCompany.from_dictionary(structure))
        insurance_risk_levels = None
        if dictionary.get('insuranceRiskLevels') != None:
            insurance_risk_levels = list()
            for structure in dictionary.get('insuranceRiskLevels'):
                insurance_risk_levels.append(easybimehlanding.models.insurance_risk_level.InsuranceRiskLevel.from_dictionary(structure))
        insurance_policy_terms = None
        if dictionary.get('insurancePolicyTerms') != None:
            insurance_policy_terms = list()
            for structure in dictionary.get('insurancePolicyTerms'):
                insurance_policy_terms.append(easybimehlanding.models.insurance_policy_term.InsurancePolicyTerm.from_dictionary(structure))
        provinces = None
        if dictionary.get('provinces') != None:
            provinces = list()
            for structure in dictionary.get('provinces'):
                provinces.append(easybimehlanding.models.province.Province.from_dictionary(structure))
        cities = dictionary.get('cities')
        city_regions = dictionary.get('cityRegions')
        shipping_types = None
        if dictionary.get('shippingTypes') != None:
            shipping_types = list()
            for structure in dictionary.get('shippingTypes'):
                shipping_types.append(easybimehlanding.models.shipping_type.ShippingType.from_dictionary(structure))
        post_types = None
        if dictionary.get('postTypes') != None:
            post_types = list()
            for structure in dictionary.get('postTypes'):
                post_types.append(easybimehlanding.models.post_type.PostType.from_dictionary(structure))
        insurance_policy_condition = easybimehlanding.models.insurance_policy_condition.InsurancePolicyCondition.from_dictionary(dictionary.get('insurancePolicyCondition')) if dictionary.get('insurancePolicyCondition') else None
        insurance_data = easybimehlanding.models.insurance_data_liability_doctor_insurance.InsuranceDataLiabilityDoctorInsurance.from_dictionary(dictionary.get('insuranceData')) if dictionary.get('insuranceData') else None

        # Return an object of this model
        return cls(has_plan,
                   activity_area,
                   expertises,
                   commitment_ceilings,
                   physical_commitment,
                   insurance_companies,
                   insurance_risk_levels,
                   insurance_policy_terms,
                   provinces,
                   cities,
                   city_regions,
                   shipping_types,
                   post_types,
                   insurance_policy_condition,
                   insurance_data)


