# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import easybimehlanding.models.travel_insurance_policy_extend

class TravelInsurancePolicyExtendView(object):

    """Implementation of the 'TravelInsurancePolicyExtendView' model.

    TODO: type model description here.

    Attributes:
        travel_insurance_policy_extend (TravelInsurancePolicyExtend): TODO:
            type description here.
        travel_insurance_policy_extend_ages (list of string): TODO: type
            description here.
        travel_insurance_policy_extend_passengers (list of string): TODO: type
            description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "travel_insurance_policy_extend":'travelInsurancePolicyExtend',
        "travel_insurance_policy_extend_ages":'travelInsurancePolicyExtendAges',
        "travel_insurance_policy_extend_passengers":'travelInsurancePolicyExtendPassengers'
    }

    def __init__(self,
                 travel_insurance_policy_extend=None,
                 travel_insurance_policy_extend_ages=None,
                 travel_insurance_policy_extend_passengers=None):
        """Constructor for the TravelInsurancePolicyExtendView class"""

        # Initialize members of the class
        self.travel_insurance_policy_extend = travel_insurance_policy_extend
        self.travel_insurance_policy_extend_ages = travel_insurance_policy_extend_ages
        self.travel_insurance_policy_extend_passengers = travel_insurance_policy_extend_passengers


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        travel_insurance_policy_extend = easybimehlanding.models.travel_insurance_policy_extend.TravelInsurancePolicyExtend.from_dictionary(dictionary.get('travelInsurancePolicyExtend')) if dictionary.get('travelInsurancePolicyExtend') else None
        travel_insurance_policy_extend_ages = dictionary.get('travelInsurancePolicyExtendAges')
        travel_insurance_policy_extend_passengers = dictionary.get('travelInsurancePolicyExtendPassengers')

        # Return an object of this model
        return cls(travel_insurance_policy_extend,
                   travel_insurance_policy_extend_ages,
                   travel_insurance_policy_extend_passengers)


