# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class TravelInsurancePolicyFilter(object):

    """Implementation of the 'TravelInsurancePolicyFilter' model.

    TODO: type model description here.

    Attributes:
        zone_ids (string): TODO: type description here.
        travel_rate_plan_id (string): TODO: type description here.
        travel_insurance_policy_extend_ages (string): TODO: type description
            here.
        travel_duration_param (string): TODO: type description here.
        birth_date_persian (string): TODO: type description here.
        insurance_extra_coverage_ids (string): TODO: type description here.
        policy_term_id (string): TODO: type description here.
        insurance_centre_sub_domain_name (string): TODO: type description
            here.
        insurance_centre_id (string): TODO: type description here.
        insurance_company_id (string): TODO: type description here.
        is_search_query (bool): TODO: type description here.
        gift_code (string): TODO: type description here.
        customer_user_id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "is_search_query":'isSearchQuery',
        "zone_ids":'zoneIds',
        "travel_rate_plan_id":'travelRatePlanId',
        "travel_insurance_policy_extend_ages":'travelInsurancePolicyExtendAges',
        "travel_duration_param":'travelDurationParam',
        "birth_date_persian":'birthDatePersian',
        "insurance_extra_coverage_ids":'insuranceExtraCoverageIds',
        "policy_term_id":'policyTermId',
        "insurance_centre_sub_domain_name":'insuranceCentreSubDomainName',
        "insurance_centre_id":'insuranceCentreId',
        "insurance_company_id":'insuranceCompanyId',
        "gift_code":'giftCode',
        "customer_user_id":'customerUserId'
    }

    def __init__(self,
                 is_search_query=None,
                 zone_ids=None,
                 travel_rate_plan_id=None,
                 travel_insurance_policy_extend_ages=None,
                 travel_duration_param=None,
                 birth_date_persian=None,
                 insurance_extra_coverage_ids=None,
                 policy_term_id=None,
                 insurance_centre_sub_domain_name=None,
                 insurance_centre_id=None,
                 insurance_company_id=None,
                 gift_code=None,
                 customer_user_id=None):
        """Constructor for the TravelInsurancePolicyFilter class"""

        # Initialize members of the class
        self.zone_ids = zone_ids
        self.travel_rate_plan_id = travel_rate_plan_id
        self.travel_insurance_policy_extend_ages = travel_insurance_policy_extend_ages
        self.travel_duration_param = travel_duration_param
        self.birth_date_persian = birth_date_persian
        self.insurance_extra_coverage_ids = insurance_extra_coverage_ids
        self.policy_term_id = policy_term_id
        self.insurance_centre_sub_domain_name = insurance_centre_sub_domain_name
        self.insurance_centre_id = insurance_centre_id
        self.insurance_company_id = insurance_company_id
        self.is_search_query = is_search_query
        self.gift_code = gift_code
        self.customer_user_id = customer_user_id


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        is_search_query = dictionary.get('isSearchQuery')
        zone_ids = dictionary.get('zoneIds')
        travel_rate_plan_id = dictionary.get('travelRatePlanId')
        travel_insurance_policy_extend_ages = dictionary.get('travelInsurancePolicyExtendAges')
        travel_duration_param = dictionary.get('travelDurationParam')
        birth_date_persian = dictionary.get('birthDatePersian')
        insurance_extra_coverage_ids = dictionary.get('insuranceExtraCoverageIds')
        policy_term_id = dictionary.get('policyTermId')
        insurance_centre_sub_domain_name = dictionary.get('insuranceCentreSubDomainName')
        insurance_centre_id = dictionary.get('insuranceCentreId')
        insurance_company_id = dictionary.get('insuranceCompanyId')
        gift_code = dictionary.get('giftCode')
        customer_user_id = dictionary.get('customerUserId')

        # Return an object of this model
        return cls(is_search_query,
                   zone_ids,
                   travel_rate_plan_id,
                   travel_insurance_policy_extend_ages,
                   travel_duration_param,
                   birth_date_persian,
                   insurance_extra_coverage_ids,
                   policy_term_id,
                   insurance_centre_sub_domain_name,
                   insurance_centre_id,
                   insurance_company_id,
                   gift_code,
                   customer_user_id)


