# -*- coding: utf-8 -*-

"""
    easybimehlanding

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from easybimehlanding.decorators import lazy_property
from easybimehlanding.configuration import Configuration
from easybimehlanding.controllers.file_manager_controller import FileManagerController
from easybimehlanding.controllers.liability_doctor_insurance_controller import LiabilityDoctorInsuranceController
from easybimehlanding.controllers.car_body_controller import CarBodyController
from easybimehlanding.controllers.electronic_equipment_insurance_controller import ElectronicEquipmentInsuranceController
from easybimehlanding.controllers.other_insurance_types_controller import OtherInsuranceTypesController
from easybimehlanding.controllers.third_party_insurance_controller import ThirdPartyInsuranceController
from easybimehlanding.controllers.motorcycle_insurance_controller import MotorcycleInsuranceController
from easybimehlanding.controllers.fire_insurance_controller import FireInsuranceController
from easybimehlanding.controllers.earthquake_insurance_controller import EarthquakeInsuranceController
from easybimehlanding.controllers.travel_insurance_controller import TravelInsuranceController
from easybimehlanding.controllers.elevator_insurance_controller import ElevatorInsuranceController
from easybimehlanding.controllers.main_controller import MainController
from easybimehlanding.controllers.combo_data_controller import ComboDataController
from easybimehlanding.controllers.tracking_damage_controller import TrackingDamageController
from easybimehlanding.controllers.footer_controller import FooterController
from easybimehlanding.controllers.insurance_policy_plan_controller import InsurancePolicyPlanController


class EasybimehlandingClient(object):

    config = Configuration

    @lazy_property
    def file_manager(self):
        return FileManagerController()

    @lazy_property
    def liability_doctor_insurance(self):
        return LiabilityDoctorInsuranceController()

    @lazy_property
    def car_body(self):
        return CarBodyController()

    @lazy_property
    def electronic_equipment_insurance(self):
        return ElectronicEquipmentInsuranceController()

    @lazy_property
    def other_insurance_types(self):
        return OtherInsuranceTypesController()

    @lazy_property
    def third_party_insurance(self):
        return ThirdPartyInsuranceController()

    @lazy_property
    def motorcycle_insurance(self):
        return MotorcycleInsuranceController()

    @lazy_property
    def fire_insurance(self):
        return FireInsuranceController()

    @lazy_property
    def earthquake_insurance(self):
        return EarthquakeInsuranceController()

    @lazy_property
    def travel_insurance(self):
        return TravelInsuranceController()

    @lazy_property
    def elevator_insurance(self):
        return ElevatorInsuranceController()

    @lazy_property
    def main(self):
        return MainController()

    @lazy_property
    def combo_data(self):
        return ComboDataController()

    @lazy_property
    def tracking_damage(self):
        return TrackingDamageController()

    @lazy_property
    def footer(self):
        return FooterController()

    @lazy_property
    def insurance_policy_plan(self):
        return InsurancePolicyPlanController()


